### ISSUE TITLE
ROS2 Galactic

### ISSUE THREAD

**Issue by vladb99** [Toni-SM/omni.add_on.ros2_bridge#1]
Hello, we are trying to test packages written in ROS2 galactic in the isaac simulator. The default ROS2 bridge that comes with the simulator doesn't support Galactic, but only Foxy. Does your bridge support ROS2 galactic? Or is there a way to configure the bridge to use Galactic instead of Foxy? Thanks!

**Comment by Toni-SM** [comment]
Hi @vladb99 

This extension (omni.add_on.ros2_bridge) uses the `rclpy` that comes with the Isaac Sim ROS2 bridge extension (omni.isaac.ros2_bridge). I don't think there is a direct way to modify the Isaac Sim ROS2 bridge and change foxy to galactic because there are some compiled files (`path_to_isaac_sim/exts/omni.isaac.ros2_bridge/bin`) on which the extension is built (`path_to_isaac_sim/exts/omni.isaac.ros2_bridge/config/extension.toml`). 

How much do you need to use that is not in foxy?

**Comment by vladb99** [comment]
It's not really about something specific that foxy doesn't have. In our project we need to switch from foxy to galactic because of a non-technical reason. Thus, we need to figure out how to make our ROS2 scripts under Galactic to also work with the simulator.
Do you know a workaround to achieve this?

**Comment by Toni-SM** [comment]
Mmmm, you can always for python (not C/C++) add the ROS2 python packages to the PYTHONPATH using the `sys` module.

For example, The next image shows the `rclpy` imported not from the Isaac Sim ROS2 bridge (because I disabled all the ROS bridges) but from the ROS2 distribution I have installed in my filesystem (as you can see when the `.__file__` property is printed). 

With this workaround, you can work with other ROS distributions inside Isaac Sim (custom extensions, script editor, standalone applications), but I think (I have not tested it) you will not be able to use the Isaac Sim ROS2 bridge features...
 
![Screenshot from 2022-04-26 23-39-04](https://user-images.githubusercontent.com/22400377/165397671-55e926e5-feba-4fc2-b7f9-386135fe447d.png)

**Comment by vladb99** [comment]
Thanks for the help!
